name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Set up Protoc
      uses: arduino/setup-protoc@v1
      
    - name: Compile Protofile
      run: protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/actions-test.proto
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
