name: Go

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      postgres-app:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: ${{secrets.TEST_POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.TEST_POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.TEST_POSTGRES_DB}}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

      postgres-test:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: ${{secrets.TEST_POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.TEST_POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.TEST_POSTGRES_DB}}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 3001:5432

    steps:
      - name: checkout
        uses: actions/checkout@v2
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Build Binary
        run: GOOS=linux GOARCH=amd64 go build -o app

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io/preimmortal/actions-test
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/preimmortal/actions-test:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}